### ISSUE TITLE
Create Reps API file

### ISSUE THREAD

**Issue by harshil1712** [obitodarky/Reps-Events-Mobile#12]
Create a Reps API file similar to [events api file](https://github.com/obitodarky/Reps-Events-Mobile/blob/dev/reps_event_app/lib/api/reps_event_api.dart). 
API for Mozilla Reps data: https://reps.mozilla.org/api/v1/rep/?limit=0&offset=0
This is related to issue #4

**Comment by arps18** [comment]
I would like to work on the issue!

**Comment by harshil1712** [comment]
Awesome, assigning it to you

**Comment by obitodarky** [comment]
This issue was solved in #29
