### ISSUE TITLE
Add Search in Reps list

### ISSUE THREAD

**Issue by obitodarky** [obitodarky/Reps-Events-Mobile#20]
Currently, it is unknown how to filter data from the Reps API( See #4 ) by name. We need to find the parameters that can be passed on the API to fetch filtered data. This then needs to be implemented in the API file (See #12 ). Once all of this is done, a search bar that filters Reps List by name must be added. (This is similar to the Events List Page)

**Comment by pransh15** [comment]
can we please use the search toolbar at the bottom?

**Comment by obitodarky** [comment]
@pransh15 I'm not sure how the top would look then. If we add it to the 
bottom, then the top part of each page will look empty.

![Screenshot 2019-07-27 at 9 02 29 PM](https://user-images.githubusercontent.com/21317964/61996452-1c7afc00-b0b2-11e9-9b9b-a852cb60d46d.png)

We can use the top space for the tabs but it hasn't been decided right now how that will look. Once the tabs design is decided then we can keep it in the bottom.

**Comment by harshil1712** [comment]
@pransh15 if we have it at the bottom, whenever the keyboard shows up it will either hide the search bar, or it will move the search bar up, overlapping with all the other widgets. And so I think the search bar on top is a better option

**Comment by obitodarky** [comment]
Fixed in #33.
