### ISSUE TITLE
Use Tabs instead of Drawer

### ISSUE THREAD

**Issue by obitodarky** [obitodarky/Reps-Events-Mobile#21]
Instead of using an App Drawer which has been implemented, it is a better idea to use Tabs. The App Drawer as such serves no purpose since we only have 3 pages. Therefore there is no such need of an App Drawer. To simplify things, we need a TabView. You learn more about Tabs in Flutter [here](https://flutter.dev/docs/cookbook/design/tabs)

**Comment by pransh15** [comment]
Tabs do seem like a better option since it makes one-handed use easier.

**Comment by Thesmader** [comment]
I would like to work on this issue.

**Comment by Thesmader** [comment]
I was wondering if I could get seme guidelines regarding where to place the tabs and dark mode switch on the screen. A bottom navigation bar could look good. I'll get to work as soon as I get a confirmation regarding this.

**Comment by obitodarky** [comment]
@Thesmader thanks for taking this issue. We had initially thought of having the tabs at the top and have the dark mode switch somewhere on the top right with a search bar at the bottom. I would suggest you have the tabs at the top.

**Comment by Thesmader** [comment]
@obitodarky thanks for the confirmation. I'm starting work now.

**Comment by Thesmader** [comment]
This is the current status of the UI. I will wait for further suggestions. Also, I think switch may not look good at top right corner. A button like the one in Twitter app could look nice.

![GIF-191002_135107](https://user-images.githubusercontent.com/34758667/66029904-d57c0d80-e51d-11e9-89b5-0d8af0f155c9.gif)
