### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by harshil1712** [obitodarky/Reps-Events-Mobile#22]
Since we are aiming to help First Time Contributors get started it will be good to have a pull request template.
The Pull Request should have the following information
- Summary 
- Screenshot (if working on UI)
- Issue No.

The template should also specify the format of the title for the PR.

**Comment by obitodarky** [comment]
@harshil1712  please check if the PR template is proper. If so, you can close this issue.

**Comment by harshil1712** [comment]
@obitodarky looks good :+1:
