### ISSUE TITLE
Add App Icon

### ISSUE THREAD

**Issue by obitodarky** [obitodarky/Reps-Events-Mobile#23]
Currently, the app has the default App Icon for Flutter. We need an App Icon for the App.

**Comment by pransh15** [comment]
![image](https://user-images.githubusercontent.com/18158596/61992479-b6c04d00-b07c-11e9-8797-b3bddf30373b.png)

this is it.

**Comment by pransh15** [comment]
please find the original files here: https://drive.google.com/drive/folders/1M80zSrx640Ve7chhrmwn08RO0s6HnN5n

closing this issue since there's nothing left here.
