### ISSUE TITLE
Add event details page

### ISSUE THREAD

**Issue by AyushBherwani1998** [obitodarky/Reps-Events-Mobile#3]
User should navigate to event details page on tapping the event tile.

**Comment by harshil1712** [comment]
I would like to take this :stuck_out_tongue:

**Comment by obitodarky** [comment]
Sure. Please leave the rest to me.

**Comment by harshil1712** [comment]
@obitodarky @AyushBherwani1998 currently we are seeing the details on when we click on the information (i) icon. Does that needs to be replaced?
Also what all details should we show, apart from the event name, description, venue, and date? Should we show the category, the event link, the owner, estimated attendees?

**Comment by obitodarky** [comment]
> @obitodarky @AyushBherwani1998 currently we are seeing the details on when we click on the information (i) icon. Does that needs to be replaced?

Yes, I think the icon can be replaced with something relevant like "see description". 

> Also what all details should we show, apart from the event name, description, venue, and date? Should we show the category, the event link, the owner, estimated attendees?

I think we should show a map of the desired venue. I don't think we should add estimated attendees but we can add a link which leads to the event page on reps portal

**Comment by AyushBherwani1998** [comment]
We don't need to replace information (i) `iconButton`, it is used to show a quick description of the event. 
On the event details page, you can show the information which is shown in the reps.mozilla.org
Example: https://reps.mozilla.org/e/everest-hack/
We can skip the estimated attendees

**Comment by obitodarky** [comment]
> We don't need to replace information (i) `iconButton`, it is used to show a quick description of the event.
> On the event details page, you can show the information which is shown in the reps.mozilla.org
> Example: https://reps.mozilla.org/e/everest-hack/

I would suggest not to include every information since it is only meant for mozillians. They don't need to know uncessary inforamtion like Estiamted attendance, Metrics, Swag Request and Goals. We can add Reps Attending the event

**Comment by harshil1712** [comment]
Do we have any wireframe for this?
