### ISSUE TITLE
Low Resolution images

### ISSUE THREAD

**Issue by obitodarky** [obitodarky/Reps-Events-Mobile#37]
**Describe the bug**
Images in the Reps Details Screen are in low resolution

**To Reproduce**
1. Start the App
2. Click on the Drawer icon `≡`
3. Go to `People`
4. Select any item from the list.
5. Image is of low resolution

**Expected behavior**
A proper image with a good resolution should be shown.

**Screenshots**
![Screenshot 2019-08-10 at 5 45 06 PM](https://user-images.githubusercontent.com/21317964/62821752-9671b180-bb97-11e9-8352-ef134baff50c.png)

**Smartphone:**
 - Device: Asus Zenfone Max Pro M1
 - OS: Android 9

**Comment by AyushBherwani1998** [comment]
The  image we are fetching from URL are of 80x80 pixels and scaling up the image results into low resolution image.

**Comment by obitodarky** [comment]
As @AyushBherwani1998 said, this seems to be the issue of the pictures itself since they are Low Res. I think the photo comes from the Mozillians API. Closing this and will make a new issue regarding the Mozillians API.
