### ISSUE TITLE
Create custom gif for loading

### ISSUE THREAD

**Issue by AyushBherwani1998** [obitodarky/Reps-Events-Mobile#39]
## Use case
Create custom gif for loading animation.  

## Proposal
The current gif leaves a white patch in dark mode.

![Screenshot_1565450947](https://user-images.githubusercontent.com/34301187/62824893-30018900-bbc1-11e9-9a8d-9eeb6594e991.png)

### Would you like to work on this issue?
No

**Comment by joaoaugustogrobe** [comment]
Hello! I'd like to work on it.

**Comment by sbis04** [comment]
I am thinking of creating the animation using **FLARE**, which would fix this issue gracefully. Give me some time to finish the animation using Flare. Also, please let me know if it is alright if I proceed with Flare animation?

**Comment by obitodarky** [comment]
@sbis04 that would be lovely! Please proceed with Flare animation

**Comment by sbis04** [comment]
I have created a pull request.
