### ISSUE TITLE
Bottom Overflowed by 97 pixels

### ISSUE THREAD

**Issue by AyushBherwani1998** [obitodarky/Reps-Events-Mobile#49]
**Describe the bug**
The bottom is overflowed by 97 pixels in About tab

**To Reproduce**

1. Go to Events or Reps tab
2. Click on the search bar to open the keyboard
3. Go to About tab 

**Expected behavior**

The keyboard shouldnot be opened when user is switching to About tab

**Screenshots**
![Screenshot_1571234022](https://user-images.githubusercontent.com/34301187/66926671-1579df00-f04c-11e9-95e9-cde2685d9947.png)

**Additional context**

To solve the issue, one can remove the focus when the index of the tab controller is changed.

**Comment by ankank30** [comment]
I want to take this issue

**Comment by AyushBherwani1998** [comment]
Great, assigning to you @ankank30
