### ISSUE TITLE
Add about Reps Page

### ISSUE THREAD

**Issue by obitodarky** [obitodarky/Reps-Events-Mobile#5]
Add the about section as seen here
https://reps.mozilla.org/

**Comment by harshil1712** [comment]
do we just include the text? the rest of the content seems to dynamic, and we will need the API to get those.

**Comment by AyushBherwani1998** [comment]
We just need to include the text.

**Comment by obitodarky** [comment]
Something like this? @AyushBherwani1998 
![Screenshot 2019-07-22 at 6 34 40 PM](https://user-images.githubusercontent.com/21317964/61634843-dee03280-acaf-11e9-8224-59d909d125a9.png)

**Comment by obitodarky** [comment]
Solved in #27
