### ISSUE TITLE
[Bug] The link is broken in README.md

### ISSUE THREAD

**Issue by nimit2801** [obitodarky/Reps-Events-Mobile#53]
**Describe the bug**

The link in broken in README.md file for Contribution Guilines

**To Reproduce**

**Expected behavior**

![contribution md](https://user-images.githubusercontent.com/53462249/95673057-02e4a800-0bc3-11eb-96f4-b7574abf6358.PNG)

**Screenshots**
![image](https://user-images.githubusercontent.com/53462249/95672945-55719480-0bc2-11eb-98c3-fa73cb20094d.png)
![image](https://user-images.githubusercontent.com/53462249/95672958-67533780-0bc2-11eb-986d-bc58b02c84a9.png)

**Comment by nimit2801** [comment]
@obitodarky I'd like to work on fixing this link issue.

**Comment by obitodarky** [comment]
Thanks for pointing it out! 
Feel free to send a PR 👍
